### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by sarafarajnasardi** [Nkca122/JuliusEncryptus#1]
When we are on the `decoder` page and Reload the website. It gives an Error Saying Page 404

**Comment by Nkca122** [comment]
Please Send a SS of The Error code and the message it also displays, on the decoder page, Also Please Check Your Internet Speed during the reload.

**Comment by sarafarajnasardi** [comment]
![Screenshot 2024-11-09 150433](https://github.com/user-attachments/assets/d0e41e5b-294a-4219-aa1d-dfb703253797)
check it!

**Comment by Nkca122** [comment]
Try again

**Comment by sarafarajnasardi** [comment]
Done! Now working properly...
